# Generated by Django 3.2.9 on 2021-11-22 03:09

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, error_messages={'unique': '이미 해당 별명을 가진 사용자가 존재합니다.'}, help_text='필수 항목이며 중복은 불가능합니다. 글자, 숫자, @/./+/-/_만 사용 가능합니다.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
