# Generated by Django 3.2.9 on 2021-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='nestedcommentreport',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ratingreport',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
