# Generated by Django 3.2.9 on 2021-11-22 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_is_netflix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dlike_users',
            field=models.ManyToManyField(blank=True, related_name='dlike_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
