# Generated by Django 3.2.9 on 2021-11-20 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reported_users',
            field=models.ManyToManyField(related_name='reported_reviews', through='reports.ReviewReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='dlike_users',
            field=models.ManyToManyField(related_name='dlike_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='like_users',
            field=models.ManyToManyField(related_name='like_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='rating',
            name='reported_users',
            field=models.ManyToManyField(related_name='reported_ratings', through='reports.RatingReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.comment'),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='dlike_users',
            field=models.ManyToManyField(related_name='dlike_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='reported_users',
            field=models.ManyToManyField(related_name='reported_nested_comments', through='reports.NestedCommentReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nestedcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='dlike_users',
            field=models.ManyToManyField(related_name='dlike_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reported_users',
            field=models.ManyToManyField(related_name='reported_comments', through='reports.CommentReport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
