# Generated by Django 3.2.9 on 2021-11-22 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dlike_users',
            field=models.ManyToManyField(blank=True, related_name='dlike_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nestedcomment',
            name='dlike_users',
            field=models.ManyToManyField(blank=True, related_name='dlike_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nestedcomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_nested_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='dlike_users',
            field=models.ManyToManyField(blank=True, related_name='dlike_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='dlike_users',
            field=models.ManyToManyField(blank=True, related_name='dlike_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
